### ISSUE TITLE
Documentation Items

### ISSUE THREAD

**Issue by TheBajaGuy** [jasonsbeer/Amiga-N2630#19]
Some items in the documentation to backfill information on, as it seems to be a little ambiguous, or is missing:

IDE section, J905 setting, implies the option of using a Cable Select (CS) pair of IDE devices.  I will make the assumption that CS is a  functional feature at this point?  If that is true, then it is implied by other wording (but not explicit) that the onboard CF interface cannot be used with the CS setting, as it is a non-CS device?  Save a few support questions by mentioning it.  It should also be written out that both potential IDE-cable devices must also support CS, have the proper cable, and be set for CS operations.

AMIX, as I always understood from the rare encounters I had, only supported the 33C93A SCSI interface of the A3000 and the A2091 for both tape and SCSI disk I/O operations.  I don't believe there is any Gayle-like IDE interface support in it, as CPU-driven disk interfaces are usually shunned by Unix/POSIX operating systems.  It may be worth a mention of having an AMIX-supported SCSI controller, such as the A2091, in the system lest someone makes an assumption that the onboard IDE may work.

Informational:

Although I believe it has become a stale build by now, my brother used to run the 68K version of NetBSD on the GVP 68030's and Series II SCSI cards.  My understanding is that the 68K NetBSD would support ANY 68030 accelerator, and at least any Zorro-configured FastRAM.  It also supported at least the 33C93A SCSI chip in an AutoConfig PIC, which meant at least the C= A2091 and the GVP Series II SCSI interfaces.  I know it was base-compatible with the A2630-based A2500 and the A3000D/T, so should be compatible with the N2630's accelerator.  I have no info on IDE support it may or may not have had.

Zorro II/III RAM settings - Has OS 2.04/2.05 for the 16-bit machines (A2000) been checked to see if it supports a Zorro III AutoConfig PIC?  I know the support for this was in the Amiga OS 3.1 and later releases.  I am not sure it was in 2.04/2.05.  It may be a good idea to check and note it.  I doubt the Zorro III FastRAM setting will work/may even crash under Kickstart 1.3, as Zorro III never existed under OS 1.3 when it was released for the 68000 machines.  The Zorro-II settings will work in all OS versions.

**Comment by jasonsbeer** [comment]
Thanks for the suggestions and information. Comments below. Its good to have the documentation peer reviewed. I will close this issue as complete, but feel free to reopen or start a new one if you see anything else.

> IDE section, J905 setting, implies the option of using a Cable Select (CS) pair of IDE devices. I will make the assumption that CS is a functional feature at this point? If that is true, then it is implied by other wording (but not explicit) that the onboard CF interface cannot be used with the CS setting, as it is a non-CS device? Save a few support questions by mentioning it. It should also be written out that both potential IDE-cable devices must also support CS, have the proper cable, and be set for CS operations.

I edited the IDE section to enhance clarity around this. 


> 
> AMIX, as I always understood from the rare encounters I had, only supported the 33C93A SCSI interface of the A3000 and the A2091 for both tape and SCSI disk I/O operations. I don't believe there is any Gayle-like IDE interface support in it, as CPU-driven disk interfaces are usually shunned by Unix/POSIX operating systems. It may be worth a mention of having an AMIX-supported SCSI controller, such as the A2091, in the system lest someone makes an assumption that the onboard IDE may work.

I added this and a link to the AMIX page.


> Although I believe it has become a stale build by now, my brother used to run the 68K version of NetBSD on the GVP 68030's and Series II SCSI cards. My understanding is that the 68K NetBSD would support ANY 68030 accelerator, and at least any Zorro-configured FastRAM. It also supported at least the 33C93A SCSI chip in an AutoConfig PIC, which meant at least the C= A2091 and the GVP Series II SCSI interfaces. I know it was base-compatible with the A2630-based A2500 and the A3000D/T, so should be compatible with the N2630's accelerator. I have no info on IDE support it may or may not have had.

Thanks for the information. The current NetBSD Amiga build supports the 68020 and greater and the A1200 built in IDE, which is Gayle. Sounds like it should work with the N2630, but we have not specifically tested it nor have I heard it discussed.

 
> Zorro II/III RAM settings - Has OS 2.04/2.05 for the 16-bit machines (A2000) been checked to see if it supports a Zorro III AutoConfig PIC? I know the support for this was in the Amiga OS 3.1 and later releases. I am not sure it was in 2.04/2.05. It may be a good idea to check and note it. I doubt the Zorro III FastRAM setting will work/may even crash under Kickstart 1.3, as Zorro III never existed under OS 1.3 when it was released for the 68000 machines. The Zorro-II settings will work in all OS versions.

Z3 AUTOCONFIG works with KS2.04 and newer. We tested it pretty well.

It is recommended in the documentation to disable Z3 RAM on the N2630 when using KS1.x. This 'disable' skips the AUTOCONFIG process, but the RAM still responds in the Z3 address space. Testing on my machines indicates it is not necessary to disable Z3 AUTOCONFIG in this case, but I feel it is best practice.
